local map = vim.keymap.set
local s = { silent = true }

map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
map("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })

map("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus left" })
map("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus right" })
map("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus down" })
map("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus up" })

map("n", "<leader>ps", "<cmd>lua vim.pack.update()<CR>", { desc = "[P]lugin [S]ync/update" })

local ok, builtin = pcall(require, "telescope.builtin")
if ok then
	map("n", "<leader>sh", builtin.help_tags, { desc = "[S]earch [H]elp" })
	map("n", "<leader>sk", builtin.keymaps, { desc = "[S]earch [K]eymaps" })
	map("n", "<leader>sf", builtin.find_files, { desc = "[S]earch [F]iles" })
	map("n", "<leader>ss", builtin.builtin, { desc = "[S]earch [S]elect Telescope" })
	map("n", "<leader>sw", builtin.grep_string, { desc = "[S]earch current [W]ord" })
	map("n", "<leader>sg", builtin.live_grep, { desc = "[S]earch by [G]rep" })
	map("n", "<leader>sd", builtin.diagnostics, { desc = "[S]earch [D]iagnostics" })
	map("n", "<leader>sr", builtin.resume, { desc = "[S]earch [R]esume" })
	map("n", "<leader>s.", builtin.oldfiles, { desc = "[S]earch Recent Files" })
	map("n", "<leader><leader>", builtin.buffers, { desc = "[ ] Find existing buffers" })
	map("n", "<leader>sn", function()
		builtin.find_files({ cwd = vim.fn.stdpath("config") })
	end, { desc = "[S]earch [N]eovim files" })
	map("n", "<leader>/", function()
		builtin.current_buffer_fuzzy_find(
			require("telescope.themes").get_dropdown({ winblend = 10, previewer = false })
		)
	end, { desc = "[/] Fuzzy search current buffer" })
	map("n", "<leader>s/", function()
		builtin.live_grep({ grep_open_files = true, prompt_title = "Live Grep in Open Files" })
	end, { desc = "[S]earch [/] in Open Files" })
end

map("n", "<leader>f", function()
	require("conform").format({ async = true, lsp_format = "fallback" })
end, { desc = "[F]ormat buffer" })
map("n", "<leader>Tf", function()
	require("toggleterm").toggle(vim.v.count1, 0, vim.uv.cwd(), "float")
end, { desc = "ToggleTerm (float)" })
map("n", "<leader>Th", function()
	require("toggleterm").toggle(vim.v.count1, 15, vim.uv.cwd(), "horizontal")
end, { desc = "ToggleTerm (horizontal)" })
map("n", "<leader>Tv", function()
	require("toggleterm").toggle(vim.v.count1, vim.o.columns * 0.4, vim.uv.cwd(), "vertical")
end, { desc = "ToggleTerm (vertical)" })
map("n", "<leader>Tn", "<cmd>ToggleTermSetName<cr>", { desc = "Set term name" })
map("n", "<leader>Ts", "<cmd>TermSelect<cr>", { desc = "Select term" })
map("n", "<leader>Tt", function()
	require("toggleterm").toggle(1, 100, vim.uv.cwd(), "tab")
end, { desc = "ToggleTerm (tab)" })

map("n", "<leader>e", function()
	require("mini.files").open()
end, { desc = "Open mini.files (cwd)" })
map("n", "<leader>E", function()
	require("mini.files").open(vim.api.nvim_buf_get_name(0))
end, { desc = "Open mini.files (current file)" })

map("n", "<F5>", function()
	require("dap").continue()
end, { desc = "Debug: Start/Continue" })
map("n", "<F1>", function()
	require("dap").step_into()
end, { desc = "Debug: Step Into" })
map("n", "<F2>", function()
	require("dap").step_over()
end, { desc = "Debug: Step Over" })
map("n", "<F3>", function()
	require("dap").step_out()
end, { desc = "Debug: Step Out" })
map("n", "<F7>", function()
	require("dapui").toggle()
end, { desc = "Debug: Toggle UI" })
map("n", "<leader>b", function()
	require("dap").toggle_breakpoint()
end, { desc = "Debug: Toggle Breakpoint" })
map("n", "<leader>B", function()
	require("dap").set_breakpoint(vim.fn.input("Breakpoint condition: "))
end, { desc = "Debug: Set Breakpoint" })
